### ISSUE TITLE
Upgrade Mocap code to use ROS2

### ISSUE THREAD

**Issue by PeterMitrano** [UM-ARM-Lab/lightweight_vicon_bridge#13]
Tasks:

 - [x] create new `vicon_interfaces` package for messages

    - [x]  Discuss: why do we want to separate out the interfaces of vicon? Is there a use case where we want to use the interface but not the actual mocap system

 - [x] update the code (zixuan/ros2 branch)
    - [x] lightweight_vicon_bridge_node.cpp
    - [x] tf_publisher_node.cpp
    - [x] raw_marker_bridge_node.cpp
 - Existing issues
     - [x] Can't link vicon_sdk properly during compilation. Need to configure LD_LIBRARY_PATH mannually. We should double check the CMakeLists.txt 
     - [x] Can't build with `colcon build --symlink-install`. Need to rebuild if launch script is modified
     - [x] attribute type of param is no longer supported, causing type mismatch problem
     - [x] Substitution doesn't work in launch script
     - [x] Double declaration error for `use_sim_time`
     - [x] Logging format is a bit messy
     - [x] "If you want a counterpart of tf::StampedTransform in tf2, you need to go with geometry_msgs::TransformStamped". Check whether they have the same structures 
 - [x] clean up raw_marker_publisher

**Comment by PeterMitrano** [comment]
@Yating05 @zxhuang97  can you finish this tomorrow or thursday?

**Comment by Yating05** [comment]
Yeah, I can do that after my Thursday’s meeting.

**Comment by PeterMitrano** [comment]
Finished with #14
